name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: angular-app
          path: dist/

      # Add deployment steps here, such as deploying to a hosting platform like Netlify, GitHub Pages, Firebase Hosting, etc.
      # Example:
      #- name: Deploy to Netlify
      #  uses: netlify/actions/cli@v1
      # with:
       #   args: deploy --prod
